### ISSUE TITLE
TrySend(Disconnected) in publish after a reconnection

### ISSUE THREAD

**Issue by opensourcegeek** [AtherEnergy/rumqtt#156]
I'm using older version of this library (0.10.0) to publish some messages, at times I hit an issue with connectivity and the connection is re-established at network level. I believe client reconnects to broken after that however when client is trying to publish message it logs message like below `write(1, "TrySend(\"Disconnected(..)\")\n", 28) = 28` and the message never reaches broker. I cannot even see this traffic when I run `tcpdump`.

Any idea where to look for that TrySend("Disconnected") issue? I'm not sure if this is a tokio/mio issue or this library. This library has changed so much and I cannot find the source for older versions here so kind of looking for some pointers to continue my investigation. Thanks.

**Comment by tekjar** [comment]
Unfortunately, I don't have the bandwidth to debug older versions. Please use the  latest version if possible and feel free to reopen this
