### ISSUE TITLE
Unclear Error Message: Notification send failed. Error = "Full(..)"

### ISSUE THREAD

**Issue by TheBestJohn** [AtherEnergy/rumqtt#158]
Looks like [this function](https://github.com/AtherEnergy/rumqtt/blob/0a95a9ac1a32ce986759e819747cfeb67efe1516/src/client/connection.rs#L493) throws an error if the max_queue is met however it's more of a status message than an error isn't it? The message is still queued for dispatch, it's just waiting on the message queue to not be full.

**Comment by tekjar** [comment]
Unfortunately no. If your notification receiver isn't keeping up with the incoming messages, you'll loose messages

**Comment by tekjar** [comment]
related #139

**Comment by TheBestJohn** [comment]
Ah I see, I was seeing "try send" as try to send to the broker.
