### ISSUE TITLE
Throttle can not be smaller than 1.

### ISSUE THREAD

**Issue by leoniloris** [AtherEnergy/rumqtt#168]
- Some brokers (such as google clout iot) has a limitation in some of its topics in which publishes should have a maximum frequency of 1 per second.

- That said, It would be good to be able to set a `throttle_period` instead of a `throttle_rate`, because this rate can not be a floating point number, and the rate of publishing gets really close to the limit some brokers can handle (disconnecting often).

Having a `throttle: u64` really limits the since flow control is something that every bit of control is useful, Is there a way to get a throttle of 0.5 (publish at a rate of 1 per 2 seconds max)?

Cheers!

**Comment by tekjar** [comment]
Thanks :)
