### ISSUE TITLE
How to shut down a client gracefully?

### ISSUE THREAD

**Issue by michaelmarconi** [AtherEnergy/rumqtt#173]
I'd like to gracefully shut down the MQTT client.  I see [an example of calling `mqtt_client.shutdown()`](https://github.com/AtherEnergy/rumqtt/blob/62b8eb60bd9b387e26422f504d94aa71783aab62/examples/shutdown.rs), however this method doesn't seem to exist on version `0.30.1` of this library?

**Comment by tekjar** [comment]
Shutdown that you see isn't graceful shutdown. Graceful shutdown isn't possible yet. I'm waiting for stable async/await to start the work.

**Comment by michaelmarconi** [comment]
OK.  Is there any way currently to cleanly shutdown the connection to the broker then?
I'm simply dropping the client, which results in an error message at the broker.

**Comment by michaelmarconi** [comment]
I've moved to the `master` branch and calling `mqtt_client.shutdown()` has the desired effect of sending a clean shutdown signal to the broker, thanks!
