### ISSUE TITLE
_try_reconnect will timeout in ~ 70 secs, in case no ACK packet is received.

### ISSUE THREAD

**Issue by creativcoder** [AtherEnergy/rumqtt#39]
So i investigated the issue about blocking connection on a random port like `test.mosquitto.org:1234` and the blocking happens exactly in [L320](https://github.com/Ather-Energy/RuMqtt/blob/1e71f3ad17537b90debf5e1a3c48de8203c71182/src/connection.rs#L320). and eventually the connection timeouts as evident from the retransmittion packets sent as shown below. The error message in particular is `Error { repr: Os { code: 110, message: "Connection timed out" } }`

![2017-02-16-161729_1920x1080_scrot](https://cloud.githubusercontent.com/assets/5155745/23008505/0cdc9aaa-f436-11e6-81a9-298d4d696ad3.png)

**Comment by tekjar** [comment]
Should be fixed in tokio2 branch
