### ISSUE TITLE
tokio2 branch's tls connection doesn't work with clean_session=false

### ISSUE THREAD

**Issue by tekjar** [AtherEnergy/rumqtt#61]

**Comment by nanomad** [comment]
I think I found it. 

I have no idea why it wasn't working as I'm not even a tokio newbie but something was going wrong in republish_unacked of connection.rs when publishes was an Vec of len 0.

**Comment by tekjar** [comment]
Ok I think there is no problem with this. I was testing this with aws iot and it doesn't seem to support persistent sessions (and I don't know how to check the reason for disconnection on aws). Tls is working for me locally.

@nanomad I think this is a different issue. I'll verify this.

**Comment by nanomad** [comment]
@tekjar You can use the free plan on [CloudMQTT](https://www.cloudmqtt.com/) to test it. 

I've configured it using the following as the CA cert bundle:

`"C:\OpenSSL-Win64\certs\cacert.pem"`

**Comment by tekjar** [comment]
@nanomad 

This is happening because `Framed` is not able to continue after handling [bounded streams](https://github.com/AtherEnergy/rumqtt/blob/tokio2/src/client/connection.rs#L189)

**Comment by nanomad** [comment]
Ah, makes sense. I'll work on it a little bit. It's a good way of learning about tokio2 anyway

**Comment by nanomad** [comment]
So, after looking at https://github.com/alexcrichton/futures-rs/issues/462 it seems like both future's join as well as sink's send_all flush and close the sink at the end which is no bueno.

I suppose the solution is to iterate over the packets sending them one by one. I'll see what I can come up...

**Comment by nanomad** [comment]
@tekjar 
Should be fixed in #67 
Took me way too much than I care to admit to figure out how to write the loop properly
