### ISSUE TITLE
Docs are outdated

### ISSUE THREAD

**Issue by gabisurita** [AtherEnergy/rumqtt#80]
The example on the docs does not match the latest api.

**Comment by tekjar** [comment]
Yeah. I'll wait for some time as tokio is moving too fast.

**Comment by aep** [comment]
docs.rs does all the hard work for you. should probably just link there. https://docs.rs/rumqtt/0.10.1/rumqtt/

**Comment by tekjar** [comment]
I'll clean up everything when async/await is out in nightly :)

**Comment by tekjar** [comment]
We can use docs.rs now :)
