### ISSUE TITLE
Update password while being connected

### ISSUE THREAD

**Issue by denizs** [AtherEnergy/rumqtt#91]
Hey there!
Is there any way to update client credentials whilst staying connected?
If not, what's the way to go here? Call `disconnect` on the client, call `set_password` on client options and start a new client with the updated options?
Best,
D

**Comment by tekjar** [comment]
The current design doesn't allow this as the connect options are passed to network thread during the initial run. I'm implementing a new design with tokio (which is private now). I'll keep this feature in mind.

**Comment by denizs** [comment]
Closed in 0.30.1
